@host=http://localhost:3000

### 查询所有用户
POST {{host}}/api/user/query_user HTTP/1.1
Content-Type: application/x-www-form-urlencoded


### 查询用户
POST {{host}}/api/user/query_user_by_id HTTP/1.1
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36

id=6

### 新增用户
POST {{host}}/api/user/add_user HTTP/1.1
Content-Type: application/json

{
    "empId": "097829",
    "userName": "zouyuejian11",
    "age": 15,
    "birthday": "2021-01-01"
}

### 更新用户
POST {{host}}/api/user/update_user HTTP/1.1
Content-Type: application/json

{
    "id": 6,
    "empId": "097829",
    "userName": "zouyuejian11",
    "age": 16,
    "birthday": "2021-02-01"
}

### 删除用户
POST {{host}}/api/user/delete_user HTTP/1.1
Content-Type: application/x-www-form-urlencoded

id=6