@host=http://localhost:3000

### 查询所有用户
POST {{host}}/api/user/query_user HTTP/1.1
Content-Type: application/x-www-form-urlencoded


### 查询用户
POST {{host}}/api/user/query_user_by_id HTTP/1.1
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36

id=9

### 新增用户
POST {{host}}/api/user/add_user HTTP/1.1
Content-Type: application/json

{
    "empId": "12072329",
    "userName": "diesel add3",
    "age": 16,
    "birthday": "2022-01-12"
}

### 更新用户
POST {{host}}/api/user/update_user HTTP/1.1
Content-Type: application/json

{
    "id": 7,
    "empId": "120722",
    "userName": "diesel update1",
    "age": 17,
    "birthday": "2021-02-02"
}

### 删除用户
POST {{host}}/api/user/delete_user HTTP/1.1
Content-Type: application/x-www-form-urlencoded

id=5