syntax = "proto3";
package org;
import "common.proto";

message AddOrgRequest {
  uint32 id = 1; // 0 表示新建，其余表示更新
  string org_code = 2;
  string org_name = 3;
}


message OrgData {
  uint32 id = 1;
  string org_code = 2;
  string org_name = 3;
  int64 update_time = 4;
}

message OrgListResponse {
  repeated OrgData orgs = 1;
}

message OrgResponse {
  bool found = 1;
  OrgData org = 2;
}

service OrgService {
  rpc AddOrg(AddOrgRequest) returns (common.IdResponse);
  rpc GetAllOrgs(common.Empty) returns (OrgListResponse);
  rpc GetOrgById(common.IdRequest) returns (OrgResponse);
  rpc DeleteOrg(common.IdRequest) returns (common.RowsAffected);
  rpc UpdateOrg(AddOrgRequest) returns (common.RowsAffected);
}
