syntax = "proto3";

package user;


message AddUserRequest {
  uint32 id = 1; // 0 表示新建，其余表示更新
  string emp_id = 2;
  string user_name = 3;
  uint32 age = 4;
  string birthday = 5;
}

message IdRequest {
  uint32 id = 1;
}

message UserData {
  uint32 id = 1;
  string emp_id = 2;
  string user_name = 3;
  uint32 age = 4;
  string birthday = 5;
  int64 create_time = 6;
  int64 update_time = 7;
}

message UserListResponse {
  repeated UserData users = 1;
}

message UserResponse {
  bool found = 1;
  UserData user = 2;
}

message RowsAffected {
  uint32 count = 1;
}

message IdResponse {
  uint32 id = 1;
}

message Empty {}

service UserService {
  rpc AddUser(AddUserRequest) returns (IdResponse);
  rpc GetAllUsers(Empty) returns (UserListResponse);
  rpc GetUserById(IdRequest) returns (UserResponse);
  rpc DeleteUser(IdRequest) returns (RowsAffected);
  rpc UpdateUser(AddUserRequest) returns (RowsAffected);
}
