syntax = "proto3";
package user;
import "org.proto";
import "common.proto";

message AddUserRequest {
  uint32 id = 1; // 0 表示新建，其余表示更新
  string emp_id = 2;
  string user_name = 3;
  uint32 age = 4;
  string birthday = 5;
}


message UserData {
  uint32 id = 1;
  string emp_id = 2;
  string user_name = 3;
  uint32 age = 4;
  string birthday = 5;
  int64 create_time = 6;
  int64 update_time = 7;
  // 👇 嵌套 OrgData
  org.OrgData org_data = 8;  // 注意：tag number 要唯一（这里用 8）
}

message UserListResponse {
  repeated UserData users = 1;
}

message UserResponse {
  bool found = 1;
  UserData user = 2;
}

service UserService {
  rpc AddUser(AddUserRequest) returns (common.IdResponse);
  rpc GetAllUsers(common.Empty) returns (UserListResponse);
  rpc GetUserById(common.IdRequest) returns (UserResponse);
  rpc DeleteUser(common.IdRequest) returns (common.RowsAffected);
  rpc UpdateUser(AddUserRequest) returns (common.RowsAffected);
}
